/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CustomersController_list"];
        put?: never;
        post: operations["CustomersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CustomersController_get"];
        put?: never;
        post?: never;
        delete: operations["CustomersController_remove"];
        options?: never;
        head?: never;
        patch: operations["CustomersController_update"];
        trace?: never;
    };
    "/api/measurement-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeasurementDefinitionsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customerId}/bikes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CustomerBikesController_list"];
        put?: never;
        post: operations["CustomerBikesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bikes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BikesController_get"];
        put?: never;
        post?: never;
        delete: operations["BikesController_remove"];
        options?: never;
        head?: never;
        patch: operations["BikesController_update"];
        trace?: never;
    };
    "/api/fits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FitsController_list"];
        put?: never;
        post: operations["FitsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FitsController_get"];
        put?: never;
        post?: never;
        delete: operations["FitsController_remove"];
        options?: never;
        head?: never;
        patch: operations["FitsController_update"];
        trace?: never;
    };
    "/api/fits/{id}/body-measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["FitsController_updateBodyMeasurements"];
        trace?: never;
    };
    "/api/fits/{id}/bike-measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["FitsController_updateBikeMeasurements"];
        trace?: never;
    };
    "/api/fits/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FitsController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        CurrentUserDto: {
            id: string;
            email: string;
            name: string;
            /** @enum {string} */
            role: "OWNER" | "FITTER";
            organization: {
                id: string;
                name: string;
                slug: string;
            };
        };
        CustomerListDto: {
            data: {
                id: string;
                firstName: string;
                lastName: string;
                email: string | null;
                phone: string | null;
                dateOfBirth: string | null;
                heightMm: number | null;
                weightGrams: number | null;
                notes: string | null;
                createdAt: string;
                updatedAt: string;
            }[];
            meta: {
                page: number;
                perPage: number;
                total: number;
                totalPages: number;
            };
        };
        CustomerDto: {
            id: string;
            firstName: string;
            lastName: string;
            email: string | null;
            phone: string | null;
            dateOfBirth: string | null;
            heightMm: number | null;
            weightGrams: number | null;
            notes: string | null;
            createdAt: string;
            updatedAt: string;
        };
        CreateCustomerDto: {
            firstName: string;
            lastName: string;
            email?: ("" | string) | null;
            phone?: string | null;
            dateOfBirth?: ("" | string) | null;
            heightMm?: ("" | number) | null;
            weightGrams?: ("" | number) | null;
            notes?: string | null;
        };
        UpdateCustomerDto: {
            firstName?: string;
            lastName?: string;
            email?: ("" | string) | null;
            phone?: string | null;
            dateOfBirth?: ("" | string) | null;
            heightMm?: ("" | number) | null;
            weightGrams?: ("" | number) | null;
            notes?: string | null;
        };
        MeasurementDefinitionListDto: {
            data: {
                /** @enum {string} */
                key: "inseam" | "torso_length" | "arm_length" | "shoulder_width" | "foot_length" | "sternal_notch_height" | "forward_flexion" | "saddle_height" | "saddle_setback" | "saddle_angle" | "saddle_nose_to_bar" | "saddle_to_bar_drop" | "stem_length" | "stem_angle" | "spacer_stack" | "bar_width" | "bar_reach" | "crank_length" | "cleat_fore_aft";
                label: string;
                /** @enum {string} */
                category: "BODY" | "BIKE";
                /** @enum {string} */
                unit: "MM" | "DECIMILLIMETRE" | "DECIDEGREE" | "GRAM";
                minValue: number;
                maxValue: number;
                helpText: string | null;
                sortOrder: number;
            }[];
        };
        BikeListDto: {
            data: {
                id: string;
                customerId: string;
                brand: string | null;
                model: string | null;
                sizeLabel: string | null;
                /** @enum {string} */
                type: "ROAD" | "TT" | "GRAVEL" | "MTB" | "OTHER";
                notes: string | null;
                createdAt: string;
                updatedAt: string;
            }[];
        };
        CreateBikeDto: {
            brand?: string | null;
            model?: string | null;
            sizeLabel?: string | null;
            /**
             * @default ROAD
             * @enum {string}
             */
            type: "ROAD" | "TT" | "GRAVEL" | "MTB" | "OTHER";
            notes?: string | null;
        };
        BikeDto: {
            id: string;
            customerId: string;
            brand: string | null;
            model: string | null;
            sizeLabel: string | null;
            /** @enum {string} */
            type: "ROAD" | "TT" | "GRAVEL" | "MTB" | "OTHER";
            notes: string | null;
            createdAt: string;
            updatedAt: string;
        };
        UpdateBikeDto: {
            brand?: string | null;
            model?: string | null;
            sizeLabel?: string | null;
            /**
             * @default ROAD
             * @enum {string}
             */
            type: "ROAD" | "TT" | "GRAVEL" | "MTB" | "OTHER";
            notes?: string | null;
        };
        FitListDto: {
            data: {
                id: string;
                customerId: string;
                bikeId: string;
                /** @enum {string} */
                status: "IN_PROGRESS" | "COMPLETED";
                /** @enum {string} */
                currentStep: "BODY" | "BIKE_BEFORE" | "BIKE_AFTER" | "REVIEW";
                reason: string | null;
                startedAt: string;
                completedAt: string | null;
                customer: {
                    id: string;
                    firstName: string;
                    lastName: string;
                };
                bike: {
                    id: string;
                    brand: string | null;
                    model: string | null;
                    sizeLabel: string | null;
                    /** @enum {string} */
                    type: "ROAD" | "TT" | "GRAVEL" | "MTB" | "OTHER";
                };
            }[];
            meta: {
                page: number;
                perPage: number;
                total: number;
                totalPages: number;
            };
        };
        FitDto: {
            id: string;
            customerId: string;
            bikeId: string;
            /** @enum {string} */
            status: "IN_PROGRESS" | "COMPLETED";
            /** @enum {string} */
            currentStep: "BODY" | "BIKE_BEFORE" | "BIKE_AFTER" | "REVIEW";
            reason: string | null;
            startedAt: string;
            completedAt: string | null;
            customer: {
                id: string;
                firstName: string;
                lastName: string;
            };
            bike: {
                id: string;
                brand: string | null;
                model: string | null;
                sizeLabel: string | null;
                /** @enum {string} */
                type: "ROAD" | "TT" | "GRAVEL" | "MTB" | "OTHER";
            };
            summary: string | null;
            createdAt: string;
            updatedAt: string;
            bodyMeasurements: {
                /** @enum {string} */
                key: "inseam" | "torso_length" | "arm_length" | "shoulder_width" | "foot_length" | "sternal_notch_height" | "forward_flexion" | "saddle_height" | "saddle_setback" | "saddle_angle" | "saddle_nose_to_bar" | "saddle_to_bar_drop" | "stem_length" | "stem_angle" | "spacer_stack" | "bar_width" | "bar_reach" | "crank_length" | "cleat_fore_aft";
                value: number;
                note: string | null;
                prefilled: boolean;
            }[];
            bikeMeasurements: {
                /** @enum {string} */
                key: "inseam" | "torso_length" | "arm_length" | "shoulder_width" | "foot_length" | "sternal_notch_height" | "forward_flexion" | "saddle_height" | "saddle_setback" | "saddle_angle" | "saddle_nose_to_bar" | "saddle_to_bar_drop" | "stem_length" | "stem_angle" | "spacer_stack" | "bar_width" | "bar_reach" | "crank_length" | "cleat_fore_aft";
                value: number;
                note: string | null;
                prefilled: boolean;
                /** @enum {string} */
                stage: "BEFORE" | "AFTER";
            }[];
        };
        CreateFitDto: {
            customerId: string;
            bikeId: string;
            reason?: string | null;
        };
        UpdateFitDto: {
            /** @enum {string} */
            currentStep?: "BODY" | "BIKE_BEFORE" | "BIKE_AFTER" | "REVIEW";
            reason?: string | null;
            summary?: string | null;
        };
        UpdateBodyMeasurementsDto: {
            measurements: {
                /** @enum {string} */
                key: "inseam" | "torso_length" | "arm_length" | "shoulder_width" | "foot_length" | "sternal_notch_height" | "forward_flexion" | "saddle_height" | "saddle_setback" | "saddle_angle" | "saddle_nose_to_bar" | "saddle_to_bar_drop" | "stem_length" | "stem_angle" | "spacer_stack" | "bar_width" | "bar_reach" | "crank_length" | "cleat_fore_aft";
                value?: ("" | number) | null;
                note?: string | null;
            }[];
        };
        UpdateBikeMeasurementsDto: {
            /** @enum {string} */
            stage: "BEFORE" | "AFTER";
            measurements: {
                /** @enum {string} */
                key: "inseam" | "torso_length" | "arm_length" | "shoulder_width" | "foot_length" | "sternal_notch_height" | "forward_flexion" | "saddle_height" | "saddle_setback" | "saddle_angle" | "saddle_nose_to_bar" | "saddle_to_bar_drop" | "stem_length" | "stem_angle" | "spacer_stack" | "bar_width" | "bar_reach" | "crank_length" | "cleat_fore_aft";
                value?: ("" | number) | null;
                note?: string | null;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserDto"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserDto"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service and database are reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomersController_list: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerListDto"];
                };
            };
        };
    };
    CustomersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDto"];
                };
            };
        };
    };
    CustomersController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDto"];
                };
            };
            /** @description No such customer in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such customer in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDto"];
                };
            };
            /** @description No such customer in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeasurementDefinitionsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementDefinitionListDto"];
                };
            };
        };
    };
    CustomerBikesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BikeListDto"];
                };
            };
            /** @description No such customer in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomerBikesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBikeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BikeDto"];
                };
            };
            /** @description No such customer in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BikesController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BikeDto"];
                };
            };
            /** @description No such bike in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BikesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bike archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such bike in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BikesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBikeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BikeDto"];
                };
            };
            /** @description No such bike in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FitsController_list: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                search?: string;
                customerId?: string;
                bikeId?: string;
                status?: "IN_PROGRESS" | "COMPLETED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitListDto"];
                };
            };
        };
    };
    FitsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFitDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitDto"];
                };
            };
            /** @description No such customer or bike in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The bike belongs to a different customer */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FitsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitDto"];
                };
            };
            /** @description No such fit in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FitsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fit archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such fit in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FitsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFitDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitDto"];
                };
            };
            /** @description No such fit in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FitsController_updateBodyMeasurements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBodyMeasurementsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitDto"];
                };
            };
            /** @description No such fit in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A measurement is unknown or out of range */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FitsController_updateBikeMeasurements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBikeMeasurementsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitDto"];
                };
            };
            /** @description No such fit in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A measurement is unknown or out of range */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FitsController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FitDto"];
                };
            };
            /** @description No such fit in this organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
